language: node_js
node_js: 
  - "stable"
script:
  - npm run build
branches:
  only:
  - master

deploy:
  provider: script
  skip-cleanup: true
  script: "./travis-deploy.sh"
  on:
    branch: master