name: Build and deploy

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 
    steps:
    - name: 'Checkout  the source code from GitHub'
      uses: actions/checkout@master
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run-script build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./dist
